# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          java:
            - 'astra/**'
            - 'benchmarks/**'
            - 'config/**'
            - 'pom.xml'
            - '.github/workflows/**'
    - name: Set up JDK 21
      if: steps.filter.outputs.java == 'true'
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        #  Currently, LTS versions of Eclipse Temurin (temurin) are cached on the GitHub Hosted Runners.
        #  When temurin releases Java 21 we can start using that again
        distribution: 'corretto'
        cache: 'maven'
    - name: Ensure code is formatted
      if: steps.filter.outputs.java == 'true'
      run: mvn -B -Dstyle.color=always com.spotify.fmt:fmt-maven-plugin:check --file astra/pom.xml
    - name: Ensure jmh benchmark code is formatted
      if: steps.filter.outputs.java == 'true'
      run: mvn -B -Dstyle.color=always com.spotify.fmt:fmt-maven-plugin:check --file benchmarks/pom.xml
    - name: Build with Maven
      if: steps.filter.outputs.java == 'true'
      run: mvn -B -Dstyle.color=always package -DskipTests --file pom.xml
    - name: Run unit tests
      if: steps.filter.outputs.java == 'true'
      run: mvn -B -Dstyle.color=always test --file pom.xml
